# Generated by Django 5.0.6 on 2024-06-28 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, null=True)),
                ('userEmail', models.CharField(blank=True, null=True)),
                ('text', models.CharField(blank=True, null=True)),
                ('isDone', models.BooleanField()),
                ('isAdminUpdated', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
