# Generated by Django 5.0.6 on 2024-06-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isAdminUpdated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
